baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Beyond Meh'
theme = "yinyang"

[params]
headTitle = "BeyondMeh"
mainSections = ["posts"]

[[params.socials]]
name = "Email Me"
icon = "mail"
link = "mailto:224660+beyondmeh@users.noreply.github.com"


[[params.socials]]
name = "Github"
icon = "github"
link = "https://github.com/beyondmeh"


[menu]
  [[menu.main]]
    name       = "About"
    url        = "about/"
  [[menu.main]]
    name       = "Colophon"
    url        = "colophon/"